// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalcInput } from "./CalcInput";
import type { CalcMode } from "./CalcMode";
import type { ParamType } from "./ParamType";
import type { StandardType } from "./StandardType";

export type CalcRequest = { standard: StandardType, mode: CalcMode, param: ParamType | null, inputs: CalcInput, };
