// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalcOutput = { value: number, unit: string, decimals: number, formula_id: string, inputs_echo: string, };
