// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalcInput = { n: number | null, a_h_change: number | null, a_h_bare: number | null, b_h_change: number | null, b_h_bare: number | null, paper_h: number | null, center_paper_h: number | null, a_shrink: number | null, b_shrink: number | null, a_reserve: number | null, b_reserve: number | null, };
