// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FullCalcOutput } from "./FullCalcOutput";

export type CalcResult = { success: boolean, data: FullCalcOutput | null, error: string | null, };
