// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalcOutput } from "./CalcOutput";

export type FullCalcOutput = { a_film: CalcOutput | null, b_film: CalcOutput | null, a_die: CalcOutput | null, b_die: CalcOutput | null, };
